//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadFarmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id { get; set; }
        public string cedulaIdentidad { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<long> telefono { get; set; }
        public string direccion { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
