//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadFarmacia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idCliente { get; set; }
        public string numeroFactura { get; set; }
        public decimal total { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
