<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CadFarmacia\CadFarmacia.csproj" />
    <ProjectReference Include="..\ClnFarmacia\ClnFarmacia.csproj" />
    <ProjectReference Include="..\CpFarmacia\CpFarmacia.csproj" />
  </ItemGroup>

</Project>
