//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadFarmacia2024
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int id { get; set; }
        public int idCompra { get; set; }
        public int idMedicamento { get; set; }
        public decimal precioCompra { get; set; }
        public decimal precioVenta { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}

